#!/usr/bin/env python
# -*- coding: utf-8 -*-
''' 
    pyasm
    ~~~~~

    :copyright: 2008 by Florian Boesch <pyalot@gmail.com>.
    :license: GNU AGPL v3 or later, see LICENSE for more details.
'''

from pyasm.main import main
import sys

if __name__ == '__main__':
    main(*sys.argv[1:])
